name = "AI Puppy Lesson 1_Jav_June26 Copy"

[files]
"upython_board.py" = ""
"my_globals.py" = "" 
"sensor_mod.py" ="" 
"print_jav.py" = "" 
"my_gif.py" = "" 
"helper_mod.py" = ""

# "core-chris/upython_board.py" = "./upython_board.py" #ORGANIZE THIS LATER!
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/restapi.py" = "restapi.py"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/file_os.py" = "file_os.py"

[js_modules.main]
"https://cdn.jsdelivr.net/npm/micro-repl@0.8.2/serial.js" = "micro_repl"
"file_library.js" = "file_library"

#"https://javier-laveaga.pyscriptapps.com/jul-15-webpage/latest/jav_will_em_core/save_jav.js" = "save_jav" #GLOBAL
# "https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/file_library.js" = "file_library" #GLOBAL, same as above
#"micro_jav.js" = "micro_repl" #LOCAL
