name = "AI Puppy Lesson 1_Jav_June26 Copy"

[files]
"upython_board.py" = ""
# "core-chris/upython_board.py" = "./upython_board.py" #ORGANIZE THIS LATER!
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/restapi.py" = "restapi.py"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/file_os.py" = "file_os.py"

# "core-chris/andrea_terminal.py" = "./andrea_terminal.py" #LOCAL
# "core-chris/restapi.py" = "./restapi.py" #LOCAL
# "core-chris/file_os.py" = "./file_os.py" #LOCAL

#COMMENT THIS OUT BEFORE COMMIT (have this for local edits)
"/my_globals.py" = "./my_globals.py" #LOCAL
"/sensor_mod.py" ="./sensor_mod.py" #LOCAL
"/print_jav.py" = "./print_jav.py" #LOCAL
"/my_gif.py" = "./my_gif.py" #LOCAL
"/helper_mod.py" = "./helper_mod.py" #LOCAL

#COMMENT THIS OUT WHILE EDITING ON LOCAL
# "https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/my_globals.py" = "./my_globals.py"
# "https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/sensor_mod.py" = "./sensor_mod.py"
# "https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/print_jav.py" = "./print_jav.py"
# "https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/my_gif.py" = "./my_gif.py"
# "https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/helper_mod.py" = "./helper_mod.py"


[js_modules.main]
"https://cdn.jsdelivr.net/npm/micro-repl@0.8.2/serial.js" = "micro_repl"
"file_library.js" = "file_library" #LOCAL

#"https://javier-laveaga.pyscriptapps.com/jul-15-webpage/latest/jav_will_em_core/save_jav.js" = "save_jav" #GLOBAL
# "https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/file_library.js" = "file_library" #GLOBAL, same as above
#"micro_jav.js" = "micro_repl" #LOCAL
